<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YttStudio.Core\YttStudio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\*.ttf" />
    <EmbeddedResource Include="Assets\Fonts\LICENSE-*.txt" />
  </ItemGroup>

  <PropertyGroup />

</Project>
